### ISSUE TITLE
check metadata for attribute definition(s)

### ISSUE THREAD

**Issue by RobLBaker** [nationalparkservice/DPchecker#61]
eml/dataset/dataTable/attributeList/attribute/attributeDefinition

-Error if blank
-Do anything with it if it's not blank? Check for anything else?

**Comment by RobLBaker** [comment]
@juddpatterson How should "blank" attribute definitions be identified? 

1) The simplest way is to make sure every attributeName in metadata has an associated element,  attributeDefinition. All data columns from .csvs are already checked to make sure they have attributes (i.e. attributeName) in the metadata (via 'test_fields_match()').  So this is a solid solution,  but it does mean you if you want to run an independent set of checks for required EML elements without the other checks, there could still be columns with missing attribute definitions (because they would also be missing attribute names). On the upside, you could run the required EML elements checks with just the metadata file and would not need to have associated data files.

2) An alternative method is to have this function perform much of the same mechanics as 'test_fields_match()'. The benefit is you could run an independent set of tests for required EML elements. The downside is this set of tests would require presence of the whole data package, not just the metadata file. And, it would render 'test_fields_match()' redundant.

**Comment by juddpatterson** [comment]
I'm leaning toward option 1 so this check wouldn't require the entire data package and perhaps the text that displays after the check could be clear that "Each attributeName has a corresponding attributeDefinition" or something along those lines.

Let me see if I'm following this fully with an example. If we implemented option 1, the CSV was missing an attributeName/attributeDefinition pair, and we ran run_congruence_checks()...it would report the missing attributeName (because the attribute was found in the CSV and not in metadata) but it wouldn't ALSO report the missing attributeDefinition. But upon adding the attributeName and rerunning, it would check for the paired definition and pass/fail.

**Comment by RobLBaker** [comment]
Yes, I think the scenario you described is how it would work.

**Comment by juddpatterson** [comment]
Sounds good to me. Just FYI, as I understand it, DataStore in the next release will extract attributeName, attributeDefinition, storageType for all attributes, and optionally (if it exists) standardUnit.

**Comment by RobLBaker** [comment]
Should there be any attempt to test whether storageType matches the attribute? Or is it OK to assume that if it's present it is likely correct? (also relevant to #62)

**Comment by RobLBaker** [comment]
Can do.  Although I think those limited variables (string, float, date, etc) are storageType, not attributeDefinition (which are just free-form text for instance: 

"Label used to identify individual sampling stations within a site. Stations are installed at each Site usually in groups of 3 or 4. Station names generally begin with a Site Name/abbreviation, followed by a number between 1 and 4."

I can implimetn those checks against a match list of acceptable storageTypes in the test_storage_type function.

**Comment by juddpatterson** [comment]
Sounds great! Thanks for interpreting my response that mixed two related topics. 😄
